
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Data.SqlClient;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string sqlConnection = "Server=tcp:joe-azure-server.database.windows.net,1433;Initial Catalog=SQLDatabaseJoe;Persist Security Info=False;User ID=potatozhb;Password=Zhao1980!@;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";

            using (var conn = new SqlConnection(sqlConnection))
            {
                using (var cmd = conn.CreateCommand())
                {
                    cmd.CommandText ="select * from SalesLT.Product";
                    conn.Open();

                    using (var reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Console.WriteLine($"ID: {reader.GetInt32(0)} , Product Name: {reader.GetString(1)} , Color: {reader.GetString(2)}");
                        }
                    }

                    Console.WriteLine("\n");
                }
            }


            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                SentimentText = @"==RUDE== Dude, you are rude upload that carl picture back, or else.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Sentiment with predicted Sentiment from sample data...\n\n");


            Console.WriteLine($"Sentiment: {1F}");
            Console.WriteLine($"SentimentText: {@"==RUDE== Dude, you are rude upload that carl picture back, or else."}");


            Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
